# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [12]:
# YOUR CODE HERE

# Creating the first array
my_array1 = np.random.randint(1, 100, size=(2, 3, 4))

# Print out shape
print(f"my_array1 dimension: {my_array1.shape}")
# Print out datatype of the elements
print(f"my_array1 contains datatype: {my_array1.dtype}")

text = "I am enrolled in section 1 of DATASCI 207."
my_array2 = np.array(text.split())
print(f"my_array2 shape: {my_array2.shape}")
print(f"my_array2 elements data type: {my_array2.dtype}")


my_array1 dimension: (2, 3, 4)
my_array1 contains datatype: int64
my_array2 shape: (9,)
my_array2 elements data type: <U8
[[[54 94 34  3]
  [85 84 49 55]
  [33 29 56 83]]

 [[32 29 95 75]
  [ 9 33  9 85]
  [78 51 80 42]]]


array([54, 94, 34,  3])

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [13]:
# YOUR CODE HERE

# Creating an array of random integers
my_array3 = np.random.randint(1, 100, size=(2, 3, 5))

# Print out shape, datatype of elements, and size
print(f"my_array3 shape: {my_array3.shape}")
print(f"my_array3 elements data type: {my_array3.dtype}")
print(f"my_array3 size: {my_array3.size}\n")

# the "size" attribute
print("Please see below markdown cell for comment on the size attribute.")


my_array3 shape: (2, 3, 5)
my_array3 elements data type: int64
my_array3 size: 30

Please see below markdown cell for comment on the size attribute.


### What does the size attribute represent? 
It represents the **number of elements** of the array, **not the dimension** as I initially thought.

---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [14]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
tabular_data = np.random.random(size=(num_samples, num_features))
print(f"The dimension is: 2-d with number of rows and cols given by {tabular_data.shape}.")



The dimension is: 2-d with number of rows and cols given by (100, 17).


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [ ]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE

image_arr = np.random.random(size=(num_images, num_rows, num_cols, num_channels))
print(f"The shape of the array is: {image_arr.shape}")

The shape of the array is: (100, 256, 256, 3)


array([[[[0.37928503, 0.57181449, 0.20789363],
         [0.14708705, 0.73961762, 0.76137301],
         [0.0552172 , 0.29176576, 0.9360238 ],
         ...,
         [0.50996156, 0.90370475, 0.17206712],
         [0.33378112, 0.71285964, 0.95439188],
         [0.36734664, 0.92167617, 0.36340469]],

        [[0.83792537, 0.8520321 , 0.16376693],
         [0.54386891, 0.55298431, 0.26368089],
         [0.95801242, 0.87645381, 0.62087411],
         ...,
         [0.87611395, 0.14536706, 0.00954818],
         [0.9295326 , 0.22229241, 0.0113653 ],
         [0.16451943, 0.33675249, 0.2505387 ]],

        [[0.81581605, 0.18965131, 0.89216353],
         [0.82936101, 0.43426261, 0.38542527],
         [0.70485152, 0.82385492, 0.35043025],
         ...,
         [0.77489365, 0.11520429, 0.47929568],
         [0.358636  , 0.29638066, 0.06260081],
         [0.15302018, 0.80508019, 0.22153236]],

        ...,

        [[0.91773108, 0.802814  , 0.48371075],
         [0.7733455 , 0.00988113, 0.67624776]

---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [35]:
# YOUR CODE HERE
# Creating the array
my_array4 = np.random.randint(0, 6, size=(3, 2))
print(my_array4)

print(50*"*")
print("Print-outs for my_array4")

print(50*"*")
print(f"Shape: {my_array4.shape}")

print(50*"*")
print(f"Sum of all elements: {my_array4.sum(axis=None)}")


print(50*"*")
print(f"Sum by column (summing row values for each col): {my_array4.sum(axis=0)}")


print(50*"*")
print(f"Sum by row (summing col values for each row)\n and convert to floats: {my_array4.sum(axis=1).astype(float)}")

print(50*"*")
print(f"First row of my_array4: {my_array4[0,]}")

print(50*"*")
print(f"Second row of my_array4: {my_array4[1]}")

print(50*"*")
print(f"Position (1, 0) -- second row and first col: {my_array4[1, 0]}")

print(50*"*")
my_array4[2, 1] = 10
print(f"Print out the modified my_array4: \n{my_array4}")

#for row in 
for row in range(my_array4.shape[0]):
    for col in range(my_array4.shape[1]):
        print(f"The element at row {row} col {col}: {my_array4[row, col]}")

[[3 2]
 [2 1]
 [1 4]]
**************************************************
Print-outs for my_array4
**************************************************
Shape: (3, 2)
**************************************************
Sum of all elements: 13
**************************************************
Sum by column (summing row values for each col): [6 7]
**************************************************
Sum by row (summing col values for each row)
 and convert to floats: [5. 3. 5.]
**************************************************
First row of my_array4: [3 2]
**************************************************
Second row of my_array4: [2 1]
**************************************************
Position (1, 0) -- second row and first col: 2
**************************************************
Print out the modified my_array4: 
[[ 3  2]
 [ 2  1]
 [ 1 10]]
The element at row 0 col 0: 3
The element at row 0 col 1: 2
The element at row 1 col 0: 2
The element at row 1 col 1: 1
The element at row 2 col 0: 1


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [4]:
# YOUR CODE HERE
pixel_arr = np.random.random(size=(3, 2))
print("3 by 2 pixel array:\n", pixel_arr)

print(50*"*")
years_arr = np.array([year for year in range(1991, 2018, 1)])
print("years_arr:\n", years_arr)

print(50*"*")
zeros_arr = np.zeros(shape=(3, 5, 10))
print("zeros_arr:\n", zeros_arr)

print(50*"*")
ones_arr = np.ones(shape=(3, 5, 10))
print("ones_arr:\n", ones_arr)

print(50*"*")
constant_arr = 5 * np.ones(shape=(2, 4))
print("Array of constants:\n", constant_arr)

print(50*"*")
nsample_arr = np.random.randn(10)
print("10-sample from standard normal:\n", nsample_arr)

3 by 2 pixel array:
 [[0.14038694 0.19810149]
 [0.80074457 0.96826158]
 [0.31342418 0.69232262]]
**************************************************
years_arr:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
zeros_arr:
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
**************************************************
ones_arr:
 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [5]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [13]:
# YOUR CODE HERE

# Task 1
print("Task 1: years_3d.")
years_3d = years.reshape(3, 3, 3)
print("Shape:", years_3d.shape)
print(years_3d)

# Task 2
print(50*"*")
print("Task 2: years_1d:")
years_1d = years_3d.reshape((27,))
print("Shape:", years_1d.shape)
print(years_1d)

# Task 3
print(50*"*")
print("Task 3: years_2d")
years_2d = years_1d.reshape(1, -1)
print("Shape:", years_2d.shape)
print(years_2d)

# Task 4
print(50*"*")
print("Task 4: back to years_1d")
years_1d = years_2d.reshape(-1)
print("Shape:", years_1d.shape)
print(years_1d)



Task 1: years_3d.
Shape: (3, 3, 3)
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
**************************************************
Task 2: years_1d:
Shape: (27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
Task 3: years_2d
Shape: (1, 27)
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
**************************************************
Task 4: back to years_1d
Shape: (27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [17]:
# YOUR CODE HERE

ex_arr1 = np.array([1, 2])
ex_arr2 = np.array([3, 4])
list3 = [num for num in range(10)]
np.concatenate((ex_arr1, ex_arr2))

array([1, 2, 3, 4])

---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [ ]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

In [ ]:
# adding a scalar
years + 2

In [ ]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

In [ ]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [ ]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [ ]:
# YOUR CODE HERE

----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [ ]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [ ]:
# YOUR CODE HERE