# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. Comment on the type of its elements.

In [2]:
# YOUR CODE HERE

# Creating the first array of integers
my_array1 = np.random.randint(1, 100, size=(2, 3, 4))

# Print out shape
print(f"my_array1 (integer) dimension: {my_array1.shape}")
# Print out datatype of the elements
print(f"my_array1 elements datatype: {my_array1.dtype}")

# Create a text with numbers to be converted to a numpy array
text = "I am enrolled in section 1 of DATASCI 207."

# Convert text to numpy array
my_array2 = np.array(text.split())

# Print out shape and datatype
print(f"my_array2 shape: {my_array2.shape}")
print(f"my_array2 elements data type: {my_array2.dtype}")
print("Please see comment on datatype below in the markdown cell")


my_array1 (integer) dimension: (2, 3, 4)
my_array1 elements datatype: int64
my_array2 shape: (9,)
my_array2 elements data type: <U8
Please see comment on datatype below in the markdown cell


### Comment on datatype of my_array2
The list (which is then converted to NumPy array) consists of strings and integers. NumPy enforces a uniform/homogeneous datatype for all elements in one array. Hence "<8" means the datatype is Unicode less than 8 characters long.

---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
# YOUR CODE HERE

# Creating an array of random integers
my_array3 = np.random.randint(1, 100, size=(2, 3, 5))

# Print out shape, datatype of elements, and size
print(f"my_array3 shape: {my_array3.shape}")

print(f"my_array3 size: {my_array3.size}")

print(f"my_array3 elements data type: {my_array3.dtype}")

# the "size" attribute
print("Please see below markdown cell for comment on the size attribute.")


my_array3 shape: (2, 3, 5)
my_array3 size: 30
my_array3 elements data type: int64
Please see below markdown cell for comment on the size attribute.


### Comment on what does the size attribute represent? 
It represents the **number of elements** of the array, **not the dimension** as I initially thought.

---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

# YOUR CODE HERE
tabular_data = np.random.random(size=(num_samples, num_features))

# Print out shape
print(f"The dimension is: 2-d with number of rows and cols given by {tabular_data.shape}.")


The dimension is: 2-d with number of rows and cols given by (100, 17).


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

# YOUR CODE HERE

image_arr = np.random.random(size=(num_images, num_rows, num_cols, num_channels))
print(f"The shape of the array is: {image_arr.shape}")

The shape of the array is: (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over elements in the array. Print the output.

In [6]:
# YOUR CODE HERE
# Creating the array
my_array4 = np.random.randint(0, 6, size=(3, 2))
print("Print out a 3-by-2 integer array")
print(my_array4)

# Header for print-outs
print(50*"*")
print("Print-outs for my_array4")

# Shape
print(50*"*")
print(f"Shape: {my_array4.shape}")

# Sum of all elements
print(50*"*")
print(f"Sum of all elements: {my_array4.sum(axis=None)}")

# Sum by col
print(50*"*")
print(f"Sum by column (summing row values for each col): {my_array4.sum(axis=0)}")

# Sum by row
print(50*"*")
print(f"Sum by row (summing col values for each row)\n and convert to floats: {my_array4.sum(axis=1).astype(float)}")

# Slice out first row
print(50*"*")
print(f"First row of my_array4: {my_array4[0,]}")

# Slice out second row (without comma)
print(50*"*")
print(f"Second row of my_array4: {my_array4[1]}")

# Slice the element at row 2 col 1 (position (1, 0))
print(50*"*")
print(f"Position (1, 0) -- second row and first col: {my_array4[1, 0]}")

# Change the element at row 3 col 2 (position (2, 1))
print(50*"*")
my_array4[2, 1] = 10
print(f"Print out the modified my_array4: \n{my_array4}")

# Print out all elements in a nested loop
print(50*"*")
print("Print out all elements by loops")
for row in range(my_array4.shape[0]):
    for col in range(my_array4.shape[1]):
        print(f"The element at row {row} col {col}: {my_array4[row, col]}")

Print out a 3-by-2 integer array
[[4 5]
 [3 1]
 [1 0]]
**************************************************
Print-outs for my_array4
**************************************************
Shape: (3, 2)
**************************************************
Sum of all elements: 14
**************************************************
Sum by column (summing row values for each col): [8 6]
**************************************************
Sum by row (summing col values for each row)
 and convert to floats: [9. 4. 1.]
**************************************************
First row of my_array4: [4 5]
**************************************************
Second row of my_array4: [3 1]
**************************************************
Position (1, 0) -- second row and first col: 3
**************************************************
Print out the modified my_array4: 
[[ 4  5]
 [ 3  1]
 [ 1 10]]
**************************************************
Print out all elements by loops
The element at row 0 col 0: 4
The 

You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
# YOUR CODE HERE

# Create a (3, 2) np array
pixel_arr = np.random.random(size=(3, 2))
print("3 by 2 pixel array:\n", pixel_arr)

# Create (27,) numpy array representing years
print(50*"*")
years_arr = np.array([year for year in range(1991, 2018, 1)])
print("years_arr:\n", years_arr)

# Create (3, 5, 10) array of zeros
print(50*"*")
zeros_arr = np.zeros(shape=(3, 5, 10))
print("zeros_arr:\n", zeros_arr)

# Create (3, 5, 10) ones
print(50*"*")
ones_arr = np.ones(shape=(3, 5, 10))
print("ones_arr:\n", ones_arr)

# Create a constant array using np.ones()
print(50*"*")
constant_arr = 5 * np.ones(shape=(2, 4))
print("Array of constants:\n", constant_arr)

# Create a normal 10-sample
print(50*"*")
nsample_arr = np.random.randn(10)
print("10-sample from standard normal:\n", nsample_arr)

3 by 2 pixel array:
 [[0.10084977 0.74242288]
 [0.14053669 0.91298156]
 [0.94157853 0.23588587]]
**************************************************
years_arr:
 [1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
zeros_arr:
 [[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
**************************************************
ones_arr:
 [[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d;
2. Convert the years_3d array to a flat 1D array. Call this array years_1d;
3. Add a new axis (in front) to the years_1d array. Call this array years_2d;
4. Remove the first axis from years_2d array. Call this array years_1d.

For each exercise print the array and its shape.

In [9]:
# YOUR CODE HERE

# Task 1
print("Task 1, years_3d:")
years_3d = years.reshape(3, 3, 3)
print("Shape:", years_3d.shape)
print(years_3d)

# Task 2
print(50*"*")
print("Task 2, years_1d:")
years_1d = years_3d.reshape((27,))
print("Shape:", years_1d.shape)
print(years_1d)

# Task 3
print(50*"*")
print("Task 3, years_2d")
years_2d = years_1d.reshape(1, -1)
print("Shape:", years_2d.shape)
print(years_2d)

# Task 4
print(50*"*")
print("Task 4, back to years_1d:")
years_1d = years_2d.reshape(-1)
print("Shape:", years_1d.shape)
print(years_1d)

Task 1, years_3d:
Shape: (3, 3, 3)
[[[1991 1992 1993]
  [1994 1995 1996]
  [1997 1998 1999]]

 [[2000 2001 2002]
  [2003 2004 2005]
  [2006 2007 2008]]

 [[2009 2010 2011]
  [2012 2013 2014]
  [2015 2016 2017]]]
**************************************************
Task 2, years_1d:
Shape: (27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]
**************************************************
Task 3, years_2d
Shape: (1, 27)
[[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
  2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]]
**************************************************
Task 4, back to years_1d:
Shape: (27,)
[1991 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004
 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016 2017]


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
# YOUR CODE HERE

# First create some arrays to be used in the 8 examples
one_d_1 = np.array([1, 2])
one_d_2 = np.array([4, 6])
two_by_one_1 = np.array([[7], [11]])
two_by_one_2 = np.array([[13], [17]])

one_by_two = np.array([[3, 5]])
two_by_three = np.array([[100, 200, 300], [400, 500, 600]])


# Example 1 Simple concat of 1-d array
print(50*"*")
print(f"Concat 1: concat {one_d_1} and {one_d_2} along axis 0")
print(np.concatenate((one_d_1, one_d_2), axis=0))
print("Shape:", np.concatenate((one_d_1, one_d_2), axis=0).shape)

# Example 2 concat of arrays of different size (only differ in the axis in which they are concatenated)
print(50*"*")
print(f"Concat 2: concat {two_by_three} and {two_by_one_1} along axis 1")
print(np.concatenate((two_by_three, two_by_one_1), axis=1))
print("Shape:", np.concatenate((two_by_three, two_by_one_1), axis=1).shape)

# Example 3 concat of two two-by-one arrays along axis 0 - pile up
print(50*"*")
print(f"Concat 3: concat {two_by_one_1} and {two_by_one_2} along axis 0")
print(np.concatenate((two_by_one_1, two_by_one_2), axis=0))
print("Shape:", np.concatenate((two_by_one_1, two_by_one_2), axis=0).shape)


# Example 4 mixed - first stack two arrays, then concat the result with another array
print(50*"*")
print("Concat 4 (mix): ")
print(f"First STACK {one_d_1} and {one_d_2} along axis 0, then CONCAT with {two_by_one_1}")
print(np.concatenate(((np.stack((one_d_1, one_d_2), axis=0)), two_by_one_1), axis=1))
print("Shape:", np.concatenate(((np.stack((one_d_1, one_d_2), axis=0)), two_by_one_1), axis=1).shape)

######
######

# Example 5 simple stack
print(50*"*")
print(50*"*")
print(f"Stack 1: stacking {one_d_1} and {one_d_2} along axis 0")
print(np.stack((one_d_1, one_d_2), axis=0))
print("Shape:", np.stack((one_d_1, one_d_2), axis=0).shape)

# Example 6 insert new axis on the right
print(50*"*")
print(f"Stack 2: stacking {one_d_1} and {one_d_2} along axis 1")
print("Note that here I am stacking two 1-d array along a NEW axis.")
print(np.stack((one_d_1, one_d_2), axis=1))
print("Shape:", np.stack((one_d_1, one_d_2), axis=1).shape)

# Example 7 Stacking the same array
print(50*"*")
print(f"Stack 3: stacking {one_by_two} and {one_by_two} along axis 0")
print("Note that here I am stacking two 1-d array along a NEW axis ON THE LEFT.")
print(np.stack((one_by_two, one_by_two), axis=0))
print("Shape:", np.stack((one_by_two, one_by_two), axis=0).shape)

# Example 8
print(50*"*")
print(f"Stack 4: stacking {one_by_two} and {one_by_two} along axis 2 - thereby creating a third dimension")
#print("Note that here I am stacking two 1-d array along a NEW axis.")
print(np.stack((one_by_two, one_by_two), axis=2))
print("Shape:", np.stack((one_by_two, one_by_two), axis=2).shape)


**************************************************
Concat 1: concat [1 2] and [4 6] along axis 0
[1 2 4 6]
Shape: (4,)
**************************************************
Concat 2: concat [[100 200 300]
 [400 500 600]] and [[ 7]
 [11]] along axis 1
[[100 200 300   7]
 [400 500 600  11]]
Shape: (2, 4)
**************************************************
Concat 3: concat [[ 7]
 [11]] and [[13]
 [17]] along axis 0
[[ 7]
 [11]
 [13]
 [17]]
Shape: (4, 1)
**************************************************
Concat 4 (mix): 
First STACK [1 2] and [4 6] along axis 0, then CONCAT with [[ 7]
 [11]]
[[ 1  2  7]
 [ 4  6 11]]
Shape: (2, 3)
**************************************************
**************************************************
Stack 1: stacking [1 2] and [4 6] along axis 0
[[1 2]
 [4 6]]
Shape: (2, 2)
**************************************************
Stack 2: stacking [1 2] and [4 6] along axis 1
Note that here I am stacking two 1-d array along a NEW axis.
[[1 4]
 [2 6]]
Shape: (2, 2)
****

---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.08368618, 0.88018825, 0.04493259, 0.19677207],
       [0.38641006, 0.7924523 , 0.83026932, 0.52744027],
       [0.43324002, 0.32505719, 0.90160506, 0.97803112],
       [0.02535133, 0.61968638, 0.18608397, 0.5568769 ],
       [0.49198251, 0.35157804, 0.9148281 , 0.54715167],
       [0.64938821, 0.0883671 , 0.3285821 , 0.4128847 ],
       [0.41640329, 0.48054915, 0.61344155, 0.93495809],
       [0.31005036, 0.52894759, 0.00261089, 0.48046996],
       [0.05477829, 0.37005834, 0.1784386 , 0.23647096],
       [0.24407468, 0.01520346, 0.73229583, 0.21794808]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
# YOUR CODE HERE

# Compute mean and std for each col (axis=0), keeping the (1, 4) shape
col_mean_arr = my_array.mean(axis=0, keepdims=True)
col_std_arr = my_array.std(axis=0, keepdims=True)

print(50*"*")
print("Shape, mean:", col_mean_arr.shape)
print("Shape, std:", col_std_arr.shape)
print("Mean of each col:\n", col_mean_arr)
print("Std of each col:\n", col_std_arr)

# Remove mean
centered_arr = my_array - col_mean_arr

# Scale by std
centered_scaled_arr = centered_arr / col_std_arr

# Print the standardized array and shape

print(50*"*")
print("Standardized array:\n", centered_scaled_arr)
print("Shape:", centered_scaled_arr.shape)


**************************************************
Shape, mean: (1, 4)
Shape, std: (1, 4)
Mean of each col:
 [[0.30953649 0.44520878 0.4733088  0.50890038]]
Std of each col:
 [[0.19554416 0.26259856 0.34466858 0.25923732]]
**************************************************
Standardized array:
 [[-1.15498366  1.65644271 -1.24286412 -1.20402539]
 [ 0.39312637  1.32233598  1.03566306  0.07151706]
 [ 0.63261172 -0.45754855  1.24263213  1.80965743]
 [-1.45330429  0.66442711 -0.83333626  0.18506794]
 [ 0.93301695 -0.35655465  1.28099665  0.14755317]
 [ 1.73797938 -1.35888666 -0.41990107 -0.37037755]
 [ 0.54650979  0.13457944  0.40657245  1.64350453]
 [ 0.0026279   0.31888525 -1.36565365 -0.10966947]
 [-1.30281673 -0.28617994 -0.85551808 -1.05088813]
 [-0.33476742 -1.63750069  0.75140888 -1.12233959]]
Shape: (10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
# YOUR CODE HERE

# 1 Crop by using a border of size 1
print(50*"*")
print("Crop margin by 1:\n", my_image[1:-1, 1:-1])

# 2 Crop by using a border of size 2
print(50*"*")
print("Crop margin by 2:\n", my_image[2:-2, 2:-2])

# 3 Reverse the col order
print(50*"*")
print("Columns reverted:\n", my_image[:,:: -1])

# 4 Set to 0.5 using filter
print(50*"*")
#my_image[my_image % 2 == 0] = 0.5
my_image2 = my_image.copy()
my_image2[my_image % 2 == 0 ] = 0.5
print("Set to 0.5 if divisible by 2:\n", my_image2)
print("Comment: in this particular case only 0 is divisible by 2.")


**************************************************
Crop margin by 1:
 [[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
**************************************************
Crop margin by 2:
 [[0.48]]
**************************************************
Columns reverted:
 [[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
**************************************************
Set to 0.5 if divisible by 2:
 [[0.5  0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]
Comment: in this particular case only 0 is divisible by 2.
